### ISSUE TITLE
Stuck on a PHP install choice

### ISSUE THREAD

**Issue by filiptronicek** [luizbills/gitpod-wordpress#12]
Hello everyone,
I tried to use the provided .gitpod.yml and .gitpod.dockerfile files but it seems that the PHP installation is halted and I cannot seem to find a way to get around this. Any ideas?

![image](https://user-images.githubusercontent.com/29888641/103363786-4bbe4580-4abc-11eb-8b76-01878c30617c.png)

**Comment by luizbills** [comment]
Fixed.
Thanks for reporting.
