### ISSUE TITLE
Is PHP debug working?

### ISSUE THREAD

**Issue by eostis** [luizbills/gitpod-wordpress#8]
Hi,

I cannot get the debug mode working. Did someone succeed?

**Comment by luizbills** [comment]
Debug mode is enabled by default.
https://github.com/luizbills/gitpod-wordpress/blob/master/conf/wp-config.php#L24-L26

Just call the `error_log`. I tested here and works fine.

**Comment by eostis** [comment]
Sorry for that. I meant the "PHP debug" mode, with breakpoints.

I noticed that xdebug is installed in the image, and the apache2 php.ini is updated. But nothing happens.

**Comment by luizbills** [comment]
Oh my bad!

So... I never used the vs code's debugger with PHP. But if you find a fix, let me know.

**Comment by eostis** [comment]
I will. 

By the way, many thanks! I'm a WP developer, and this is going to change my life. A fresh environment from a git branch in one click is a dream.

**Comment by eostis** [comment]
I can debug now, and stop at breakpoints while loading a WordPress page.

A few lines of codes to add at the end of .gitpod.dockerfile:
```
USER root
RUN echo "xdebug.remote_enable = 1" >> /etc/php/7.4/apache2/conf.d/20-xdebug.ini && \
echo "xdebug.remote_log='/workspace/gitpod-wordpress/public_html/xdebug.log'" >> /etc/php/7.4/apache2/conf.d/20-xdebug.ini && \
echo "xdebug.remote_autostart = 1" >> /etc/php/7.4/apache2/conf.d/20-xdebug.ini && \
echo "xdebug.remote_host='0.0.0.0'" >> /etc/php/7.4/apache2/conf.d/20-xdebug.ini
USER gitpod
```

The launch.json:
```
{
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        }
    ]
}
```

A short video:
![gitpod-wordpress-debug](https://user-images.githubusercontent.com/1785759/94056445-986bf380-fdde-11ea-96a7-cde4021084cd.gif)

**Comment by luizbills** [comment]
@eostis thanks, sir! Now we can use breakpoints
